spring.application.name=QAirlines
server.port= 8080


spring.datasource.url=jdbc:mysql://autorack.proxy.rlwy.net:58776/q_airlines?createDatabaseIfNotExist=true&useSSL=true
spring.datasource.username=root
spring.datasource.password=PhwgSCdaEBzjcexPXRvfDeWKmGjwnGUK

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# /api-docs endpoint custom path
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


spring.security.oauth2.client.registration.google.client-id=620934045592-5i9c52grv0p9gp0k6hjlj25iiol67d7i.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google}
spring.security.oauth2.client.registration.google.client-name=Google

# OAuth2 Provider configuration for Google
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo

jwt.secret = 7ce484cd2871dd50aec1fec41fef7012efd4994e23f500dafdbf9cd17c554f85